FROM godamri/swoole-php8.1-alpine:1.2
USER root
WORKDIR /var/www/app/

RUN echo "UTC" > /etc/timezone

#dev only
RUN apk add nodejs npm nano

COPY ./conf/supervisor/conf.d/worker-dev.conf /etc/supervisor/conf.d/worker.conf
COPY ./conf/supervisor/conf.d/octane-dev.conf /etc/supervisor/conf.d/octane.conf
COPY ./conf/php/php.ini /usr/local/etc/php/conf.d/999-custom.ini

COPY ./appsrc /var/www/app/

RUN composer install --no-dev

RUN npm install chokidar --no-optional

RUN chown -R nobody.nobody /var/www/app

USER nobody

RUN ln -sf /dev/stdout /var/www/app/storage/logs/laravel.log

EXPOSE 8080
CMD ["supervisord", "-c", "/etc/supervisor/supervisord.conf"]